remote_theme: riggraz/no-style-please
plugins:
  - jekyll-remote-theme

title: "issu's sites"
description: "There's not much here but a few sites of mine."

theme_config:
  appearance: "dark"
  lowercase_titles: true
